language: python

python:
  - "2.7"

services:
  - mongodb

install:
  - pip install -r requirements.txt

script:
  - python test/test_top_page.py
  - python test/test_artifact_page.py
  - python test/test_model.py

