language: python

python:
  - "2.7"

services:
  - mongodb

install:
  - pip install flask --use-mirrors
  - pip install pymongo --use-mirrors

script:
  - python test/test_top_page.py
  - python test/test_artifact_page.py
  - python test/test_model.py

